/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Device.as).
 */

package moos.ssds.metadata {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class DeviceBase implements IExternalizable, IMetadataObject, IDescription, IResourceOwner {

        private var _description:String;
        private var _deviceType:DeviceType;
        private var _id:Number;
        private var _infoUrlList:String;
        private var _mfgModel:String;
        private var _mfgName:String;
        private var _mfgSerialNumber:String;
        private var _name:String;
        private var _person:Person;
        private var _resources:ListCollectionView;
        private var _uuid:String;
        private var _version:Number;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set deviceType(value:DeviceType):void {
            _deviceType = value;
        }
        public function get deviceType():DeviceType {
            return _deviceType;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set infoUrlList(value:String):void {
            _infoUrlList = value;
        }
        public function get infoUrlList():String {
            return _infoUrlList;
        }

        public function set mfgModel(value:String):void {
            _mfgModel = value;
        }
        public function get mfgModel():String {
            return _mfgModel;
        }

        public function set mfgName(value:String):void {
            _mfgName = value;
        }
        public function get mfgName():String {
            return _mfgName;
        }

        public function set mfgSerialNumber(value:String):void {
            _mfgSerialNumber = value;
        }
        public function get mfgSerialNumber():String {
            return _mfgSerialNumber;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set person(value:Person):void {
            _person = value;
        }
        public function get person():Person {
            return _person;
        }

        public function set resources(value:ListCollectionView):void {
            _resources = value;
        }
        public function get resources():ListCollectionView {
            return _resources;
        }

        public function set uuid(value:String):void {
            _uuid = value;
        }
        public function get uuid():String {
            return _uuid;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        public function get version():Number {
            return _version;
        }

        public function readExternal(input:IDataInput):void {
            _description = input.readObject() as String;
            _deviceType = input.readObject() as DeviceType;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _infoUrlList = input.readObject() as String;
            _mfgModel = input.readObject() as String;
            _mfgName = input.readObject() as String;
            _mfgSerialNumber = input.readObject() as String;
            _name = input.readObject() as String;
            _person = input.readObject() as Person;
            _resources = input.readObject() as ListCollectionView;
            _uuid = input.readObject() as String;
            _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_description);
            output.writeObject(_deviceType);
            output.writeObject(_id);
            output.writeObject(_infoUrlList);
            output.writeObject(_mfgModel);
            output.writeObject(_mfgName);
            output.writeObject(_mfgSerialNumber);
            output.writeObject(_name);
            output.writeObject(_person);
            output.writeObject(_resources);
            output.writeObject(_uuid);
            output.writeObject(_version);
        }
    }
}