/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Metadata.as).
 */

package moos.ssds.metadata {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class MetadataBase implements IExternalizable {

        private var _dataContainerGroups:ListCollectionView;
        private var _dataContainers:ListCollectionView;
        private var _dataProducerGroups:ListCollectionView;
        private var _dataProducers:ListCollectionView;
        private var _deployments:ListCollectionView;
        private var _devices:ListCollectionView;
        private var _events:ListCollectionView;
        private var _keywords:ListCollectionView;
        private var _persons:ListCollectionView;
        private var _processRuns:ListCollectionView;
        private var _resources:ListCollectionView;
        private var _softwares:ListCollectionView;
        private var _standardDomains:ListCollectionView;
        private var _standardKeywords:ListCollectionView;
        private var _standardReferenceScales:ListCollectionView;
        private var _standardUnits:ListCollectionView;
        private var _standardVariables:ListCollectionView;

        public function set dataContainerGroups(value:ListCollectionView):void {
            _dataContainerGroups = value;
        }
        public function get dataContainerGroups():ListCollectionView {
            return _dataContainerGroups;
        }

        public function set dataContainers(value:ListCollectionView):void {
            _dataContainers = value;
        }
        public function get dataContainers():ListCollectionView {
            return _dataContainers;
        }

        public function set dataProducerGroups(value:ListCollectionView):void {
            _dataProducerGroups = value;
        }
        public function get dataProducerGroups():ListCollectionView {
            return _dataProducerGroups;
        }

        public function set dataProducers(value:ListCollectionView):void {
            _dataProducers = value;
        }
        public function get dataProducers():ListCollectionView {
            return _dataProducers;
        }

        public function set deployments(value:ListCollectionView):void {
            _deployments = value;
        }
        public function get deployments():ListCollectionView {
            return _deployments;
        }

        public function set devices(value:ListCollectionView):void {
            _devices = value;
        }
        public function get devices():ListCollectionView {
            return _devices;
        }

        public function set events(value:ListCollectionView):void {
            _events = value;
        }
        public function get events():ListCollectionView {
            return _events;
        }

        public function set keywords(value:ListCollectionView):void {
            _keywords = value;
        }
        public function get keywords():ListCollectionView {
            return _keywords;
        }

        public function set persons(value:ListCollectionView):void {
            _persons = value;
        }
        public function get persons():ListCollectionView {
            return _persons;
        }

        public function set processRuns(value:ListCollectionView):void {
            _processRuns = value;
        }
        public function get processRuns():ListCollectionView {
            return _processRuns;
        }

        public function set resources(value:ListCollectionView):void {
            _resources = value;
        }
        public function get resources():ListCollectionView {
            return _resources;
        }

        public function set softwares(value:ListCollectionView):void {
            _softwares = value;
        }
        public function get softwares():ListCollectionView {
            return _softwares;
        }

        public function set standardDomains(value:ListCollectionView):void {
            _standardDomains = value;
        }
        public function get standardDomains():ListCollectionView {
            return _standardDomains;
        }

        public function set standardKeywords(value:ListCollectionView):void {
            _standardKeywords = value;
        }
        public function get standardKeywords():ListCollectionView {
            return _standardKeywords;
        }

        public function set standardReferenceScales(value:ListCollectionView):void {
            _standardReferenceScales = value;
        }
        public function get standardReferenceScales():ListCollectionView {
            return _standardReferenceScales;
        }

        public function set standardUnits(value:ListCollectionView):void {
            _standardUnits = value;
        }
        public function get standardUnits():ListCollectionView {
            return _standardUnits;
        }

        public function set standardVariables(value:ListCollectionView):void {
            _standardVariables = value;
        }
        public function get standardVariables():ListCollectionView {
            return _standardVariables;
        }

        public function readExternal(input:IDataInput):void {
            _dataContainerGroups = input.readObject() as ListCollectionView;
            _dataContainers = input.readObject() as ListCollectionView;
            _dataProducerGroups = input.readObject() as ListCollectionView;
            _dataProducers = input.readObject() as ListCollectionView;
            _deployments = input.readObject() as ListCollectionView;
            _devices = input.readObject() as ListCollectionView;
            _events = input.readObject() as ListCollectionView;
            _keywords = input.readObject() as ListCollectionView;
            _persons = input.readObject() as ListCollectionView;
            _processRuns = input.readObject() as ListCollectionView;
            _resources = input.readObject() as ListCollectionView;
            _softwares = input.readObject() as ListCollectionView;
            _standardDomains = input.readObject() as ListCollectionView;
            _standardKeywords = input.readObject() as ListCollectionView;
            _standardReferenceScales = input.readObject() as ListCollectionView;
            _standardUnits = input.readObject() as ListCollectionView;
            _standardVariables = input.readObject() as ListCollectionView;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_dataContainerGroups);
            output.writeObject(_dataContainers);
            output.writeObject(_dataProducerGroups);
            output.writeObject(_dataProducers);
            output.writeObject(_deployments);
            output.writeObject(_devices);
            output.writeObject(_events);
            output.writeObject(_keywords);
            output.writeObject(_persons);
            output.writeObject(_processRuns);
            output.writeObject(_resources);
            output.writeObject(_softwares);
            output.writeObject(_standardDomains);
            output.writeObject(_standardKeywords);
            output.writeObject(_standardReferenceScales);
            output.writeObject(_standardUnits);
            output.writeObject(_standardVariables);
        }
    }
}