/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (StandardVariable.as).
 */

package moos.ssds.metadata {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class StandardVariableBase implements IExternalizable, IMetadataObject, IDescription {

        private var _description:String;
        private var _id:Number;
        private var _name:String;
        private var _namespaceUriString:String;
        private var _referenceScale:String;
        private var _standardUnits:ListCollectionView;
        private var _version:Number;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set namespaceUriString(value:String):void {
            _namespaceUriString = value;
        }
        public function get namespaceUriString():String {
            return _namespaceUriString;
        }

        public function set referenceScale(value:String):void {
            _referenceScale = value;
        }
        public function get referenceScale():String {
            return _referenceScale;
        }

        public function set standardUnits(value:ListCollectionView):void {
            _standardUnits = value;
        }
        public function get standardUnits():ListCollectionView {
            return _standardUnits;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        public function get version():Number {
            return _version;
        }

        public function readExternal(input:IDataInput):void {
            _description = input.readObject() as String;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _name = input.readObject() as String;
            _namespaceUriString = input.readObject() as String;
            _referenceScale = input.readObject() as String;
            _standardUnits = input.readObject() as ListCollectionView;
            _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_description);
            output.writeObject(_id);
            output.writeObject(_name);
            output.writeObject(_namespaceUriString);
            output.writeObject(_referenceScale);
            output.writeObject(_standardUnits);
            output.writeObject(_version);
        }
    }
}