/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (StandardUnit.as).
 */

package moos.ssds.metadata {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class StandardUnitBase implements IExternalizable, IMetadataObject, IDescription {

        private var _description:String;
        private var _id:Number;
        private var _longName:String;
        private var _name:String;
        private var _symbol:String;
        private var _version:Number;

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set longName(value:String):void {
            _longName = value;
        }
        public function get longName():String {
            return _longName;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set symbol(value:String):void {
            _symbol = value;
        }
        public function get symbol():String {
            return _symbol;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        public function get version():Number {
            return _version;
        }

        public function readExternal(input:IDataInput):void {
            _description = input.readObject() as String;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _longName = input.readObject() as String;
            _name = input.readObject() as String;
            _symbol = input.readObject() as String;
            _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_description);
            output.writeObject(_id);
            output.writeObject(_longName);
            output.writeObject(_name);
            output.writeObject(_symbol);
            output.writeObject(_version);
        }
    }
}