# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='ssds-device-packet.proto',
  package='moos.ssds.io',
  serialized_pb='\n\x18ssds-device-packet.proto\x12\x0cmoos.ssds.io\"\xc4\x02\n\rMessagePacket\x12\x10\n\x08sourceID\x18\x01 \x01(\x03\x12\x10\n\x08parentID\x18\x02 \x01(\x03\x12\x12\n\npacketType\x18\x03 \x01(\x05\x12\x15\n\rpacketSubType\x18\x04 \x01(\x03\x12\x1e\n\x16metadataSequenceNumber\x18\x05 \x01(\x03\x12\x1e\n\x16\x64\x61taDescriptionVersion\x18\x06 \x01(\x03\x12\x18\n\x10timestampSeconds\x18\x07 \x01(\x03\x12\x1c\n\x14timestampNanoseconds\x18\x08 \x01(\x03\x12\x16\n\x0esequenceNumber\x18\t \x01(\x03\x12\x11\n\tbufferLen\x18\n \x01(\x05\x12\x13\n\x0b\x62ufferBytes\x18\x0b \x01(\x0c\x12\x14\n\x0c\x62ufferTwoLen\x18\x0c \x01(\x05\x12\x16\n\x0e\x62ufferTwoBytes\x18\r \x01(\x0c\x42%\n\x0cmoos.ssds.ioB\x15SSDSDevicePacketProto')




_MESSAGEPACKET = descriptor.Descriptor(
  name='MessagePacket',
  full_name='moos.ssds.io.MessagePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sourceID', full_name='moos.ssds.io.MessagePacket.sourceID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parentID', full_name='moos.ssds.io.MessagePacket.parentID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packetType', full_name='moos.ssds.io.MessagePacket.packetType', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packetSubType', full_name='moos.ssds.io.MessagePacket.packetSubType', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='metadataSequenceNumber', full_name='moos.ssds.io.MessagePacket.metadataSequenceNumber', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dataDescriptionVersion', full_name='moos.ssds.io.MessagePacket.dataDescriptionVersion', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestampSeconds', full_name='moos.ssds.io.MessagePacket.timestampSeconds', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestampNanoseconds', full_name='moos.ssds.io.MessagePacket.timestampNanoseconds', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='moos.ssds.io.MessagePacket.sequenceNumber', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bufferLen', full_name='moos.ssds.io.MessagePacket.bufferLen', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bufferBytes', full_name='moos.ssds.io.MessagePacket.bufferBytes', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bufferTwoLen', full_name='moos.ssds.io.MessagePacket.bufferTwoLen', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bufferTwoBytes', full_name='moos.ssds.io.MessagePacket.bufferTwoBytes', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=367,
)



class MessagePacket(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEPACKET
  
  # @@protoc_insertion_point(class_scope:moos.ssds.io.MessagePacket)

# @@protoc_insertion_point(module_scope)
