// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssds-device-packet.proto

package moos.ssds.io;

public final class SSDSDevicePacketProto {
  private SSDSDevicePacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class MessagePacket extends
      com.google.protobuf.GeneratedMessage {
    // Use MessagePacket.newBuilder() to construct.
    private MessagePacket() {
      initFields();
    }
    private MessagePacket(boolean noInit) {}
    
    private static final MessagePacket defaultInstance;
    public static MessagePacket getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessagePacket getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moos.ssds.io.SSDSDevicePacketProto.internal_static_moos_ssds_io_MessagePacket_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moos.ssds.io.SSDSDevicePacketProto.internal_static_moos_ssds_io_MessagePacket_fieldAccessorTable;
    }
    
    // optional int64 sourceID = 1;
    public static final int SOURCEID_FIELD_NUMBER = 1;
    private boolean hasSourceID;
    private long sourceID_ = 0L;
    public boolean hasSourceID() { return hasSourceID; }
    public long getSourceID() { return sourceID_; }
    
    // optional int64 parentID = 2;
    public static final int PARENTID_FIELD_NUMBER = 2;
    private boolean hasParentID;
    private long parentID_ = 0L;
    public boolean hasParentID() { return hasParentID; }
    public long getParentID() { return parentID_; }
    
    // optional int32 packetType = 3;
    public static final int PACKETTYPE_FIELD_NUMBER = 3;
    private boolean hasPacketType;
    private int packetType_ = 0;
    public boolean hasPacketType() { return hasPacketType; }
    public int getPacketType() { return packetType_; }
    
    // optional int64 packetSubType = 4;
    public static final int PACKETSUBTYPE_FIELD_NUMBER = 4;
    private boolean hasPacketSubType;
    private long packetSubType_ = 0L;
    public boolean hasPacketSubType() { return hasPacketSubType; }
    public long getPacketSubType() { return packetSubType_; }
    
    // optional int64 metadataSequenceNumber = 5;
    public static final int METADATASEQUENCENUMBER_FIELD_NUMBER = 5;
    private boolean hasMetadataSequenceNumber;
    private long metadataSequenceNumber_ = 0L;
    public boolean hasMetadataSequenceNumber() { return hasMetadataSequenceNumber; }
    public long getMetadataSequenceNumber() { return metadataSequenceNumber_; }
    
    // optional int64 dataDescriptionVersion = 6;
    public static final int DATADESCRIPTIONVERSION_FIELD_NUMBER = 6;
    private boolean hasDataDescriptionVersion;
    private long dataDescriptionVersion_ = 0L;
    public boolean hasDataDescriptionVersion() { return hasDataDescriptionVersion; }
    public long getDataDescriptionVersion() { return dataDescriptionVersion_; }
    
    // optional int64 timestampSeconds = 7;
    public static final int TIMESTAMPSECONDS_FIELD_NUMBER = 7;
    private boolean hasTimestampSeconds;
    private long timestampSeconds_ = 0L;
    public boolean hasTimestampSeconds() { return hasTimestampSeconds; }
    public long getTimestampSeconds() { return timestampSeconds_; }
    
    // optional int64 timestampNanoseconds = 8;
    public static final int TIMESTAMPNANOSECONDS_FIELD_NUMBER = 8;
    private boolean hasTimestampNanoseconds;
    private long timestampNanoseconds_ = 0L;
    public boolean hasTimestampNanoseconds() { return hasTimestampNanoseconds; }
    public long getTimestampNanoseconds() { return timestampNanoseconds_; }
    
    // optional int64 sequenceNumber = 9;
    public static final int SEQUENCENUMBER_FIELD_NUMBER = 9;
    private boolean hasSequenceNumber;
    private long sequenceNumber_ = 0L;
    public boolean hasSequenceNumber() { return hasSequenceNumber; }
    public long getSequenceNumber() { return sequenceNumber_; }
    
    // optional int32 bufferLen = 10;
    public static final int BUFFERLEN_FIELD_NUMBER = 10;
    private boolean hasBufferLen;
    private int bufferLen_ = 0;
    public boolean hasBufferLen() { return hasBufferLen; }
    public int getBufferLen() { return bufferLen_; }
    
    // optional bytes bufferBytes = 11;
    public static final int BUFFERBYTES_FIELD_NUMBER = 11;
    private boolean hasBufferBytes;
    private com.google.protobuf.ByteString bufferBytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBufferBytes() { return hasBufferBytes; }
    public com.google.protobuf.ByteString getBufferBytes() { return bufferBytes_; }
    
    // optional int32 bufferTwoLen = 12;
    public static final int BUFFERTWOLEN_FIELD_NUMBER = 12;
    private boolean hasBufferTwoLen;
    private int bufferTwoLen_ = 0;
    public boolean hasBufferTwoLen() { return hasBufferTwoLen; }
    public int getBufferTwoLen() { return bufferTwoLen_; }
    
    // optional bytes bufferTwoBytes = 13;
    public static final int BUFFERTWOBYTES_FIELD_NUMBER = 13;
    private boolean hasBufferTwoBytes;
    private com.google.protobuf.ByteString bufferTwoBytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBufferTwoBytes() { return hasBufferTwoBytes; }
    public com.google.protobuf.ByteString getBufferTwoBytes() { return bufferTwoBytes_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSourceID()) {
        output.writeInt64(1, getSourceID());
      }
      if (hasParentID()) {
        output.writeInt64(2, getParentID());
      }
      if (hasPacketType()) {
        output.writeInt32(3, getPacketType());
      }
      if (hasPacketSubType()) {
        output.writeInt64(4, getPacketSubType());
      }
      if (hasMetadataSequenceNumber()) {
        output.writeInt64(5, getMetadataSequenceNumber());
      }
      if (hasDataDescriptionVersion()) {
        output.writeInt64(6, getDataDescriptionVersion());
      }
      if (hasTimestampSeconds()) {
        output.writeInt64(7, getTimestampSeconds());
      }
      if (hasTimestampNanoseconds()) {
        output.writeInt64(8, getTimestampNanoseconds());
      }
      if (hasSequenceNumber()) {
        output.writeInt64(9, getSequenceNumber());
      }
      if (hasBufferLen()) {
        output.writeInt32(10, getBufferLen());
      }
      if (hasBufferBytes()) {
        output.writeBytes(11, getBufferBytes());
      }
      if (hasBufferTwoLen()) {
        output.writeInt32(12, getBufferTwoLen());
      }
      if (hasBufferTwoBytes()) {
        output.writeBytes(13, getBufferTwoBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSourceID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getSourceID());
      }
      if (hasParentID()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getParentID());
      }
      if (hasPacketType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getPacketType());
      }
      if (hasPacketSubType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getPacketSubType());
      }
      if (hasMetadataSequenceNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getMetadataSequenceNumber());
      }
      if (hasDataDescriptionVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getDataDescriptionVersion());
      }
      if (hasTimestampSeconds()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, getTimestampSeconds());
      }
      if (hasTimestampNanoseconds()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, getTimestampNanoseconds());
      }
      if (hasSequenceNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, getSequenceNumber());
      }
      if (hasBufferLen()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, getBufferLen());
      }
      if (hasBufferBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getBufferBytes());
      }
      if (hasBufferTwoLen()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, getBufferTwoLen());
      }
      if (hasBufferTwoBytes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getBufferTwoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static moos.ssds.io.SSDSDevicePacketProto.MessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(moos.ssds.io.SSDSDevicePacketProto.MessagePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private moos.ssds.io.SSDSDevicePacketProto.MessagePacket result;
      
      // Construct using moos.ssds.io.SSDSDevicePacketProto.MessagePacket.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new moos.ssds.io.SSDSDevicePacketProto.MessagePacket();
        return builder;
      }
      
      protected moos.ssds.io.SSDSDevicePacketProto.MessagePacket internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new moos.ssds.io.SSDSDevicePacketProto.MessagePacket();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moos.ssds.io.SSDSDevicePacketProto.MessagePacket.getDescriptor();
      }
      
      public moos.ssds.io.SSDSDevicePacketProto.MessagePacket getDefaultInstanceForType() {
        return moos.ssds.io.SSDSDevicePacketProto.MessagePacket.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public moos.ssds.io.SSDSDevicePacketProto.MessagePacket build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private moos.ssds.io.SSDSDevicePacketProto.MessagePacket buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public moos.ssds.io.SSDSDevicePacketProto.MessagePacket buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        moos.ssds.io.SSDSDevicePacketProto.MessagePacket returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moos.ssds.io.SSDSDevicePacketProto.MessagePacket) {
          return mergeFrom((moos.ssds.io.SSDSDevicePacketProto.MessagePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(moos.ssds.io.SSDSDevicePacketProto.MessagePacket other) {
        if (other == moos.ssds.io.SSDSDevicePacketProto.MessagePacket.getDefaultInstance()) return this;
        if (other.hasSourceID()) {
          setSourceID(other.getSourceID());
        }
        if (other.hasParentID()) {
          setParentID(other.getParentID());
        }
        if (other.hasPacketType()) {
          setPacketType(other.getPacketType());
        }
        if (other.hasPacketSubType()) {
          setPacketSubType(other.getPacketSubType());
        }
        if (other.hasMetadataSequenceNumber()) {
          setMetadataSequenceNumber(other.getMetadataSequenceNumber());
        }
        if (other.hasDataDescriptionVersion()) {
          setDataDescriptionVersion(other.getDataDescriptionVersion());
        }
        if (other.hasTimestampSeconds()) {
          setTimestampSeconds(other.getTimestampSeconds());
        }
        if (other.hasTimestampNanoseconds()) {
          setTimestampNanoseconds(other.getTimestampNanoseconds());
        }
        if (other.hasSequenceNumber()) {
          setSequenceNumber(other.getSequenceNumber());
        }
        if (other.hasBufferLen()) {
          setBufferLen(other.getBufferLen());
        }
        if (other.hasBufferBytes()) {
          setBufferBytes(other.getBufferBytes());
        }
        if (other.hasBufferTwoLen()) {
          setBufferTwoLen(other.getBufferTwoLen());
        }
        if (other.hasBufferTwoBytes()) {
          setBufferTwoBytes(other.getBufferTwoBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSourceID(input.readInt64());
              break;
            }
            case 16: {
              setParentID(input.readInt64());
              break;
            }
            case 24: {
              setPacketType(input.readInt32());
              break;
            }
            case 32: {
              setPacketSubType(input.readInt64());
              break;
            }
            case 40: {
              setMetadataSequenceNumber(input.readInt64());
              break;
            }
            case 48: {
              setDataDescriptionVersion(input.readInt64());
              break;
            }
            case 56: {
              setTimestampSeconds(input.readInt64());
              break;
            }
            case 64: {
              setTimestampNanoseconds(input.readInt64());
              break;
            }
            case 72: {
              setSequenceNumber(input.readInt64());
              break;
            }
            case 80: {
              setBufferLen(input.readInt32());
              break;
            }
            case 90: {
              setBufferBytes(input.readBytes());
              break;
            }
            case 96: {
              setBufferTwoLen(input.readInt32());
              break;
            }
            case 106: {
              setBufferTwoBytes(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional int64 sourceID = 1;
      public boolean hasSourceID() {
        return result.hasSourceID();
      }
      public long getSourceID() {
        return result.getSourceID();
      }
      public Builder setSourceID(long value) {
        result.hasSourceID = true;
        result.sourceID_ = value;
        return this;
      }
      public Builder clearSourceID() {
        result.hasSourceID = false;
        result.sourceID_ = 0L;
        return this;
      }
      
      // optional int64 parentID = 2;
      public boolean hasParentID() {
        return result.hasParentID();
      }
      public long getParentID() {
        return result.getParentID();
      }
      public Builder setParentID(long value) {
        result.hasParentID = true;
        result.parentID_ = value;
        return this;
      }
      public Builder clearParentID() {
        result.hasParentID = false;
        result.parentID_ = 0L;
        return this;
      }
      
      // optional int32 packetType = 3;
      public boolean hasPacketType() {
        return result.hasPacketType();
      }
      public int getPacketType() {
        return result.getPacketType();
      }
      public Builder setPacketType(int value) {
        result.hasPacketType = true;
        result.packetType_ = value;
        return this;
      }
      public Builder clearPacketType() {
        result.hasPacketType = false;
        result.packetType_ = 0;
        return this;
      }
      
      // optional int64 packetSubType = 4;
      public boolean hasPacketSubType() {
        return result.hasPacketSubType();
      }
      public long getPacketSubType() {
        return result.getPacketSubType();
      }
      public Builder setPacketSubType(long value) {
        result.hasPacketSubType = true;
        result.packetSubType_ = value;
        return this;
      }
      public Builder clearPacketSubType() {
        result.hasPacketSubType = false;
        result.packetSubType_ = 0L;
        return this;
      }
      
      // optional int64 metadataSequenceNumber = 5;
      public boolean hasMetadataSequenceNumber() {
        return result.hasMetadataSequenceNumber();
      }
      public long getMetadataSequenceNumber() {
        return result.getMetadataSequenceNumber();
      }
      public Builder setMetadataSequenceNumber(long value) {
        result.hasMetadataSequenceNumber = true;
        result.metadataSequenceNumber_ = value;
        return this;
      }
      public Builder clearMetadataSequenceNumber() {
        result.hasMetadataSequenceNumber = false;
        result.metadataSequenceNumber_ = 0L;
        return this;
      }
      
      // optional int64 dataDescriptionVersion = 6;
      public boolean hasDataDescriptionVersion() {
        return result.hasDataDescriptionVersion();
      }
      public long getDataDescriptionVersion() {
        return result.getDataDescriptionVersion();
      }
      public Builder setDataDescriptionVersion(long value) {
        result.hasDataDescriptionVersion = true;
        result.dataDescriptionVersion_ = value;
        return this;
      }
      public Builder clearDataDescriptionVersion() {
        result.hasDataDescriptionVersion = false;
        result.dataDescriptionVersion_ = 0L;
        return this;
      }
      
      // optional int64 timestampSeconds = 7;
      public boolean hasTimestampSeconds() {
        return result.hasTimestampSeconds();
      }
      public long getTimestampSeconds() {
        return result.getTimestampSeconds();
      }
      public Builder setTimestampSeconds(long value) {
        result.hasTimestampSeconds = true;
        result.timestampSeconds_ = value;
        return this;
      }
      public Builder clearTimestampSeconds() {
        result.hasTimestampSeconds = false;
        result.timestampSeconds_ = 0L;
        return this;
      }
      
      // optional int64 timestampNanoseconds = 8;
      public boolean hasTimestampNanoseconds() {
        return result.hasTimestampNanoseconds();
      }
      public long getTimestampNanoseconds() {
        return result.getTimestampNanoseconds();
      }
      public Builder setTimestampNanoseconds(long value) {
        result.hasTimestampNanoseconds = true;
        result.timestampNanoseconds_ = value;
        return this;
      }
      public Builder clearTimestampNanoseconds() {
        result.hasTimestampNanoseconds = false;
        result.timestampNanoseconds_ = 0L;
        return this;
      }
      
      // optional int64 sequenceNumber = 9;
      public boolean hasSequenceNumber() {
        return result.hasSequenceNumber();
      }
      public long getSequenceNumber() {
        return result.getSequenceNumber();
      }
      public Builder setSequenceNumber(long value) {
        result.hasSequenceNumber = true;
        result.sequenceNumber_ = value;
        return this;
      }
      public Builder clearSequenceNumber() {
        result.hasSequenceNumber = false;
        result.sequenceNumber_ = 0L;
        return this;
      }
      
      // optional int32 bufferLen = 10;
      public boolean hasBufferLen() {
        return result.hasBufferLen();
      }
      public int getBufferLen() {
        return result.getBufferLen();
      }
      public Builder setBufferLen(int value) {
        result.hasBufferLen = true;
        result.bufferLen_ = value;
        return this;
      }
      public Builder clearBufferLen() {
        result.hasBufferLen = false;
        result.bufferLen_ = 0;
        return this;
      }
      
      // optional bytes bufferBytes = 11;
      public boolean hasBufferBytes() {
        return result.hasBufferBytes();
      }
      public com.google.protobuf.ByteString getBufferBytes() {
        return result.getBufferBytes();
      }
      public Builder setBufferBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBufferBytes = true;
        result.bufferBytes_ = value;
        return this;
      }
      public Builder clearBufferBytes() {
        result.hasBufferBytes = false;
        result.bufferBytes_ = getDefaultInstance().getBufferBytes();
        return this;
      }
      
      // optional int32 bufferTwoLen = 12;
      public boolean hasBufferTwoLen() {
        return result.hasBufferTwoLen();
      }
      public int getBufferTwoLen() {
        return result.getBufferTwoLen();
      }
      public Builder setBufferTwoLen(int value) {
        result.hasBufferTwoLen = true;
        result.bufferTwoLen_ = value;
        return this;
      }
      public Builder clearBufferTwoLen() {
        result.hasBufferTwoLen = false;
        result.bufferTwoLen_ = 0;
        return this;
      }
      
      // optional bytes bufferTwoBytes = 13;
      public boolean hasBufferTwoBytes() {
        return result.hasBufferTwoBytes();
      }
      public com.google.protobuf.ByteString getBufferTwoBytes() {
        return result.getBufferTwoBytes();
      }
      public Builder setBufferTwoBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBufferTwoBytes = true;
        result.bufferTwoBytes_ = value;
        return this;
      }
      public Builder clearBufferTwoBytes() {
        result.hasBufferTwoBytes = false;
        result.bufferTwoBytes_ = getDefaultInstance().getBufferTwoBytes();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:moos.ssds.io.MessagePacket)
    }
    
    static {
      defaultInstance = new MessagePacket(true);
      moos.ssds.io.SSDSDevicePacketProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:moos.ssds.io.MessagePacket)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_moos_ssds_io_MessagePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_moos_ssds_io_MessagePacket_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ssds-device-packet.proto\022\014moos.ssds.io" +
      "\"\304\002\n\rMessagePacket\022\020\n\010sourceID\030\001 \001(\003\022\020\n\010" +
      "parentID\030\002 \001(\003\022\022\n\npacketType\030\003 \001(\005\022\025\n\rpa" +
      "cketSubType\030\004 \001(\003\022\036\n\026metadataSequenceNum" +
      "ber\030\005 \001(\003\022\036\n\026dataDescriptionVersion\030\006 \001(" +
      "\003\022\030\n\020timestampSeconds\030\007 \001(\003\022\034\n\024timestamp" +
      "Nanoseconds\030\010 \001(\003\022\026\n\016sequenceNumber\030\t \001(" +
      "\003\022\021\n\tbufferLen\030\n \001(\005\022\023\n\013bufferBytes\030\013 \001(" +
      "\014\022\024\n\014bufferTwoLen\030\014 \001(\005\022\026\n\016bufferTwoByte" +
      "s\030\r \001(\014B%\n\014moos.ssds.ioB\025SSDSDevicePacke",
      "tProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_moos_ssds_io_MessagePacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_moos_ssds_io_MessagePacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_moos_ssds_io_MessagePacket_descriptor,
              new java.lang.String[] { "SourceID", "ParentID", "PacketType", "PacketSubType", "MetadataSequenceNumber", "DataDescriptionVersion", "TimestampSeconds", "TimestampNanoseconds", "SequenceNumber", "BufferLen", "BufferBytes", "BufferTwoLen", "BufferTwoBytes", },
              moos.ssds.io.SSDSDevicePacketProto.MessagePacket.class,
              moos.ssds.io.SSDSDevicePacketProto.MessagePacket.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
