/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package moos.ssds.metadata {

    [Bindable]
    [RemoteClass(alias="moos.ssds.metadata.Event")]
    public class Event extends EventBase {
    }
}