/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package moos.ssds.metadata {

    public interface IMetadataObject {

        function set id(value:Number):void;
        function get id():Number;
    }
}