/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Person.as).
 */

package moos.ssds.metadata {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class PersonBase implements IExternalizable, IMetadataObject {

        private var _address1:String;
        private var _address2:String;
        private var _city:String;
        private var _email:String;
        private var _firstname:String;
        private var _id:Number;
        private var _organization:String;
        private var _phone:String;
        private var _state:String;
        private var _status:String;
        private var _surname:String;
        private var _userGroups:ListCollectionView;
        private var _username:String;
        private var _version:Number;
        private var _zipcode:String;

        public function set address1(value:String):void {
            _address1 = value;
        }
        public function get address1():String {
            return _address1;
        }

        public function set address2(value:String):void {
            _address2 = value;
        }
        public function get address2():String {
            return _address2;
        }

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set firstname(value:String):void {
            _firstname = value;
        }
        public function get firstname():String {
            return _firstname;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        public function get id():Number {
            return _id;
        }

        public function set organization(value:String):void {
            _organization = value;
        }
        public function get organization():String {
            return _organization;
        }

        public function set phone(value:String):void {
            _phone = value;
        }
        public function get phone():String {
            return _phone;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set surname(value:String):void {
            _surname = value;
        }
        public function get surname():String {
            return _surname;
        }

        public function set userGroups(value:ListCollectionView):void {
            _userGroups = value;
        }
        public function get userGroups():ListCollectionView {
            return _userGroups;
        }

        public function set username(value:String):void {
            _username = value;
        }
        public function get username():String {
            return _username;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        public function get version():Number {
            return _version;
        }

        public function set zipcode(value:String):void {
            _zipcode = value;
        }
        public function get zipcode():String {
            return _zipcode;
        }

        public function readExternal(input:IDataInput):void {
            _address1 = input.readObject() as String;
            _address2 = input.readObject() as String;
            _city = input.readObject() as String;
            _email = input.readObject() as String;
            _firstname = input.readObject() as String;
            _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _organization = input.readObject() as String;
            _phone = input.readObject() as String;
            _state = input.readObject() as String;
            _status = input.readObject() as String;
            _surname = input.readObject() as String;
            _userGroups = input.readObject() as ListCollectionView;
            _username = input.readObject() as String;
            _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _zipcode = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_address1);
            output.writeObject(_address2);
            output.writeObject(_city);
            output.writeObject(_email);
            output.writeObject(_firstname);
            output.writeObject(_id);
            output.writeObject(_organization);
            output.writeObject(_phone);
            output.writeObject(_state);
            output.writeObject(_status);
            output.writeObject(_surname);
            output.writeObject(_userGroups);
            output.writeObject(_username);
            output.writeObject(_version);
            output.writeObject(_zipcode);
        }
    }
}