/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package moos.ssds.metadata {

    public interface IDateRange {

        function get dateRange():IDateRange;

        function set endDate(value:Date):void;
        function get endDate():Date;

        function set startDate(value:Date):void;
        function get startDate():Date;
    }
}