/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package moos.ssds.metadata {

    import mx.collections.ListCollectionView;

    public interface IResourceOwner {

        function get resources():ListCollectionView;
    }
}